using UnityEngine;

namespace MyXonotic
{
    /// <summary>
    /// First-person weapon visual under the player camera. Instantiates the
    /// per-weapon prefabs generated by
    /// <c>MyXonotic.EditorTools.IqmWeaponImporter.GenerateWeaponAssets()</c>
    /// (Resources/Weapons/&lt;Name&gt;WeaponVisual, built from the original
    /// first-person "v_" meshes) and shows the one matching
    /// <see cref="WeaponController.Current"/>. Adds a procedural recoil kick,
    /// a short lower/raise animation on weapon switch, a gentle walk bob, and
    /// plays the weapon's original fire/switch sounds.
    ///
    /// Meshes are static (frame 0 / bind pose): no skeletal weapon animation is
    /// played. The importer records which source mesh produced each prefab.
    /// </summary>
    public sealed class WeaponView : MonoBehaviour
    {
        public WeaponController Controller;

        /// <summary>Local rest position/rotation this component returns to between kicks.</summary>
        public Vector3 RestLocalPosition = new Vector3(0.28f, -0.22f, 0.45f);
        public Vector3 RestLocalEulerAngles = Vector3.zero;

        [Header("Recoil (simple, procedural)")]
        public float KickBackDistance = 0.06f;
        public float KickPitchDegrees = 4f;
        public float KickRecoverySpeed = 10f;

        [Header("Switch animation")]
        public float SwitchDuration = 0.28f;
        public float SwitchDropDistance = 0.35f;

        readonly GameObject[] _visualInstances = new GameObject[WeaponController.WeaponCount];
        AudioSource _audioSource;
        WeaponType _shownWeapon = (WeaponType)(-1);

        Vector3 _kickOffset;
        float _kickPitch;
        float _switchTimer; // counts down; >0 means the raise animation is running
        Player _player;

        void Awake()
        {
            if (Controller == null) Controller = GetComponentInParent<WeaponController>();
            _player = GetComponentInParent<Player>();
            _audioSource = GetComponent<AudioSource>();
            if (_audioSource == null) _audioSource = gameObject.AddComponent<AudioSource>();
            _audioSource.playOnAwake = false;
            _audioSource.spatialBlend = 0f; // first-person weapon: 2D, not positional
            LoadVisuals();
            transform.localPosition = RestLocalPosition;
            transform.localRotation = Quaternion.Euler(RestLocalEulerAngles);
        }

        void OnEnable()
        {
            if (Controller != null) Controller.WeaponChanged += OnWeaponChanged;
        }

        void OnDisable()
        {
            if (Controller != null) Controller.WeaponChanged -= OnWeaponChanged;
        }

        void OnWeaponChanged(WeaponType previous, WeaponType current)
        {
            _switchTimer = SwitchDuration;
            var clip = WeaponAudio.Common("weapon_switch");
            if (clip != null && _audioSource != null) _audioSource.PlayOneShot(clip, 0.7f);
        }

        void LoadVisuals()
        {
            for (int i = 0; i < WeaponController.WeaponCount; i++)
            {
                string resource = "Weapons/" + (WeaponType)i + "WeaponVisual";
                var prefab = Resources.Load<GameObject>(resource);
                if (prefab == null)
                {
                    Debug.LogWarning("[WeaponView] Missing generated prefab \"" + resource +
                        "\". Run MyXonotic/Import/Generate Weapon Visuals in the Editor first.");
                    continue;
                }
                var instance = Instantiate(prefab, transform);
                instance.SetActive(false);
                _visualInstances[i] = instance;
            }
        }

        void Update()
        {
            if (Controller != null) RefreshVisibility(Controller.Current);
            if (ArenaBootstrap.IsPaused) return;

            float dt = Time.deltaTime;
            float t = 1f - Mathf.Exp(-KickRecoverySpeed * dt);
            _kickOffset = Vector3.Lerp(_kickOffset, Vector3.zero, t);
            _kickPitch = Mathf.Lerp(_kickPitch, 0f, t);

            // Switch: weapon rises from below over SwitchDuration.
            float drop = 0f;
            if (_switchTimer > 0f)
            {
                _switchTimer -= dt;
                float k = Mathf.Clamp01(_switchTimer / SwitchDuration);
                drop = SwitchDropDistance * k * k;
            }

            // Walk bob from the player's horizontal speed.
            Vector3 bob = Vector3.zero;
            if (_player != null && _player.IsGrounded)
            {
                var v = _player.Velocity; v.y = 0f;
                float speed01 = Mathf.Clamp01(v.magnitude / Player.WalkSpeed);
                float phase = Time.time * 9f;
                bob = new Vector3(Mathf.Sin(phase) * 0.012f, -Mathf.Abs(Mathf.Cos(phase)) * 0.01f, 0f) * speed01;
            }

            transform.localPosition = RestLocalPosition + _kickOffset + bob + Vector3.down * drop;
            transform.localRotation = Quaternion.Euler(RestLocalEulerAngles + new Vector3(-_kickPitch + drop * 40f, 0f, 0f));
        }

        void RefreshVisibility(WeaponType current)
        {
            if (current == _shownWeapon) return;
            for (int i = 0; i < WeaponController.WeaponCount; i++)
                if (_visualInstances[i] != null) _visualInstances[i].SetActive(i == (int)current);
            _shownWeapon = current;
        }

        /// <summary>Procedural recoil kick after a successful shot.</summary>
        public void Kick()
        {
            float heavy = Controller != null && Controller.CurrentDef.Primary.SplashRadius > 2f ? 1.8f : 1f;
            _kickOffset = new Vector3(0f, 0f, -KickBackDistance * heavy);
            _kickPitch = KickPitchDegrees * heavy;
        }

        /// <summary>Plays the current weapon's original fire (or alt-fire) sound.</summary>
        public void PlayFireSound(bool alt = false)
        {
            if (_audioSource == null || Controller == null) return;
            var clip = WeaponAudio.Fire(Controller.Current, alt);
            if (clip != null) _audioSource.PlayOneShot(clip);
        }
    }
}
