using UnityEngine;

namespace MyXonotic
{
    /// <summary>
    /// First-person weapon visual: a small runtime component meant to sit under
    /// the player's <see cref="Camera"/> transform. It instantiates the
    /// per-weapon prefabs generated by
    /// <c>MyXonotic.EditorTools.IqmWeaponImporter.GenerateWeaponAssets()</c>
    /// (Resources/Weapons/&lt;Name&gt;WeaponVisual) and swaps which one is
    /// visible to follow <see cref="WeaponController.Current"/>.
    ///
    /// Honesty note (see IqmWeaponImporter and ThirdParty/Xonotic/data/resource-notes.md):
    /// with only the committed bounded resource pack available, there is no
    /// compiled first-person ("v_") mesh for any weapon, only the world/pickup
    /// ("g_") model — what this component shows for Blaster/Rocket in that case
    /// is that world model held up in view, not a verified first-person weapon
    /// model. IqmWeaponImporter upgrades to a genuine "v_" mesh automatically
    /// (and records that it did, in its WeaponAssetResult report) if one is
    /// reachable through XONOTIC_CONTENT_ROOTS/ExternalContent at generation
    /// time; this component itself cannot tell which case produced the prefab
    /// it loaded. <see cref="WeaponType.Rifle"/> has no bounded model or sound
    /// at all and is intentionally left empty (nothing is shown) rather than
    /// reusing another weapon's mesh for it.
    ///
    /// This component does not read WeaponController's private cooldown state,
    /// fire projectiles, or play sounds on its own initiative for gameplay
    /// timing — it only reacts to the public <see cref="WeaponController.Current"/>
    /// field it polls, plus explicit calls the owner (Player/WeaponController/
    /// LocalBuild bootstrap) makes into <see cref="Kick"/> / <see cref="PlayFireSound"/>.
    /// </summary>
    public sealed class WeaponView : MonoBehaviour
    {
        /// <summary>
        /// Optional explicit wiring; if left null, resolved from an ancestor
        /// via GetComponentInParent (this component is expected to live under
        /// the player's camera, itself under the same hierarchy as
        /// WeaponController, e.g. Player root -> ... -> Camera -> WeaponView).
        /// </summary>
        public WeaponController Controller;

        /// <summary>Local rest position/rotation this component returns to between kicks.</summary>
        public Vector3 RestLocalPosition = new Vector3(0.28f, -0.22f, 0.45f);
        public Vector3 RestLocalEulerAngles = Vector3.zero;

        [Header("Recoil (simple, procedural — not a real animation)")]
        public float KickBackDistance = 0.06f;
        public float KickPitchDegrees = 4f;
        public float KickRecoverySpeed = 10f;

        [Header("Audio (optional; clips come from Resources/Weapons, generated by IqmWeaponImporter)")]
        public bool AutoAddAudioSource = true;

        readonly GameObject[] _visualInstances = new GameObject[WeaponTypeCount];
        readonly AudioClip[][] _weaponClips = new AudioClip[WeaponTypeCount][];
        AudioSource _audioSource;
        WeaponType _shownWeapon = (WeaponType)(-1);

        Vector3 _kickOffset;
        float _kickPitch;

        const int WeaponTypeCount = 3; // matches WeaponController.WeaponType: Blaster, Rifle, Rocket

        // Resource-relative names, matching IqmWeaponImporter's ResourcesRoot layout
        // (Assets/MyXonotic/Resources/Weapons/<Name>...). Rifle intentionally has
        // no prefab/clip entries: no bounded weapon model exists for it, and this
        // view must not silently substitute another weapon's mesh for it.
        static readonly string[] PrefabResourceNames =
        {
            "Weapons/BlasterWeaponVisual", // WeaponType.Blaster
            null,                          // WeaponType.Rifle - no bounded model; left empty on purpose
            "Weapons/RocketWeaponVisual"   // WeaponType.Rocket
        };

        static readonly string[][] FireClipResourceNames =
        {
            new[] { "Weapons/Blaster_lasergun_fire" },                                  // Blaster
            null,                                                                        // Rifle
            new[] { "Weapons/Rocket_rocket_fire", "Weapons/Rocket_rocket_fly", "Weapons/Rocket_rocket_impact" } // Rocket
        };

        void Awake()
        {
            if (Controller == null) Controller = GetComponentInParent<WeaponController>();
            if (AutoAddAudioSource)
            {
                _audioSource = GetComponent<AudioSource>();
                if (_audioSource == null) _audioSource = gameObject.AddComponent<AudioSource>();
                _audioSource.playOnAwake = false;
                _audioSource.spatialBlend = 0f; // first-person weapon: 2D, not positional
            }
            LoadVisuals();
            transform.localPosition = RestLocalPosition;
            transform.localRotation = Quaternion.Euler(RestLocalEulerAngles);
        }

        void LoadVisuals()
        {
            for (int i = 0; i < WeaponTypeCount; i++)
            {
                if (PrefabResourceNames[i] == null) continue;
                var prefab = Resources.Load<GameObject>(PrefabResourceNames[i]);
                if (prefab == null)
                {
                    Debug.LogWarning("[WeaponView] Missing generated prefab \"" + PrefabResourceNames[i] +
                        "\". Run MyXonotic/Import/Generate Weapon Visuals in the Editor first.");
                    continue;
                }
                var instance = Instantiate(prefab, transform);
                instance.SetActive(false);
                _visualInstances[i] = instance;

                if (FireClipResourceNames[i] != null)
                {
                    var clips = new AudioClip[FireClipResourceNames[i].Length];
                    for (int c = 0; c < clips.Length; c++)
                        clips[c] = Resources.Load<AudioClip>(FireClipResourceNames[i][c]);
                    _weaponClips[i] = clips;
                }
            }
        }

        void Update()
        {
            if (Controller != null) RefreshVisibility(Controller.Current);

            // Simple, non-physical recoil recovery: exponential decay back to rest.
            // This is a development placeholder gesture, not a keyframed/verified
            // weapon animation.
            float t = 1f - Mathf.Exp(-KickRecoverySpeed * Time.deltaTime);
            _kickOffset = Vector3.Lerp(_kickOffset, Vector3.zero, t);
            _kickPitch = Mathf.Lerp(_kickPitch, 0f, t);
            transform.localPosition = RestLocalPosition + _kickOffset;
            transform.localRotation = Quaternion.Euler(RestLocalEulerAngles + new Vector3(-_kickPitch, 0f, 0f));
        }

        void RefreshVisibility(WeaponType current)
        {
            if (current == _shownWeapon) return;
            for (int i = 0; i < WeaponTypeCount; i++)
                if (_visualInstances[i] != null) _visualInstances[i].SetActive(i == (int)current);
            _shownWeapon = current;
        }

        /// <summary>
        /// Public hook for the owner (e.g. WeaponController.TryFire's caller,
        /// or a future LocalBuild-wired input handler) to trigger a simple,
        /// non-physical recoil kick after a successful shot. Safe to call even
        /// when the current weapon has no loaded visual.
        /// </summary>
        public void Kick()
        {
            _kickOffset = new Vector3(0f, 0f, -KickBackDistance);
            _kickPitch = KickPitchDegrees;
        }

        /// <summary>
        /// Public hook to play one of the imported fire/impact sounds for the
        /// currently-shown weapon by index into <see cref="FireClipResourceNames"/>
        /// (0 = primary fire for both bounded weapons). Silently does nothing if
        /// no AudioSource/clip is available, since audio is optional here.
        /// </summary>
        public void PlayFireSound(int clipIndex = 0)
        {
            if (_audioSource == null || Controller == null) return;
            var clips = _weaponClips[(int)Controller.Current];
            if (clips == null || clipIndex < 0 || clipIndex >= clips.Length || clips[clipIndex] == null) return;
            _audioSource.PlayOneShot(clips[clipIndex]);
        }
    }
}
