using UnityEngine;

namespace MyXonotic
{
    /// <summary>
    /// First-person weapon visual under the player camera.
    ///
    /// dev.11: each weapon is shown through its original animated
    /// <c>h_&lt;weapon&gt;</c> rig (<see cref="WeaponRigInfo"/>, generated by
    /// <c>WeaponRigImporter</c>): a <see cref="CharacterAnimator"/> plays the
    /// Xonotic fire / fire2 / idle / reload clips. Skeleton-only rigs carry the
    /// static <c>v_</c> visual on their <c>weapon</c> joint; DarkPlaces rigs
    /// (Electro, Crylink, Mortar, Hagar, Devastator) render their own skinned
    /// gun. A muzzle flash is spawned at the rig's <c>shot</c> joint. Weapons
    /// without a rig fall back to the dev.8 static prefab
    /// (Resources/Weapons/&lt;Name&gt;WeaponVisual) with the procedural kick only.
    /// The whole view also gets a procedural recoil kick, a lower/raise on
    /// switch and a walk bob, and plays the weapon's original sounds.
    /// </summary>
    public sealed class WeaponView : MonoBehaviour
    {
        public WeaponController Controller;

        /// <summary>Rest pose for weapons WITHOUT an animated rig (static v_ prefab only).</summary>
        public Vector3 RestLocalPosition = new Vector3(0.28f, -0.22f, 0.45f);
        /// <summary>
        /// Rest pose for rigged weapons. Xonotic draws the h_ model at the view
        /// origin — the grip offset (right / down) is authored into the model.
        /// </summary>
        public Vector3 RigRestLocalPosition = new Vector3(0f, 0.04f, 0.05f);
        public Vector3 RestLocalEulerAngles = Vector3.zero;

        [Header("Recoil (simple, procedural)")]
        public float KickBackDistance = 0.06f;
        public float KickPitchDegrees = 4f;
        public float KickRecoverySpeed = 10f;

        [Header("Switch animation")]
        public float SwitchDuration = 0.28f;
        public float SwitchDropDistance = 0.35f;

        readonly GameObject[] _visualInstances = new GameObject[WeaponController.WeaponCount];
        readonly GameObject[] _rigRoots = new GameObject[WeaponController.WeaponCount];
        readonly CharacterAnimator[] _animators = new CharacterAnimator[WeaponController.WeaponCount];
        readonly Transform[] _shotJoints = new Transform[WeaponController.WeaponCount];
        readonly WeaponRigInfo[] _rigInfos = new WeaponRigInfo[WeaponController.WeaponCount];
        AudioSource _audioSource;
        WeaponType _shownWeapon = (WeaponType)(-1);

        Vector3 _kickOffset;
        float _kickPitch;
        float _switchTimer; // counts down; >0 means the raise animation is running
        Player _player;

        /// <summary>Number of weapons that loaded an animated rig (tests / diagnostics).</summary>
        public int RiggedWeaponCount { get { int c = 0; foreach (var a in _animators) if (a != null) c++; return c; } }
        public CharacterAnimator AnimatorFor(WeaponType w) => _animators[(int)w];
        public WeaponRigInfo RigInfoFor(WeaponType w) => _rigInfos[(int)w];
        public Transform ShotJointFor(WeaponType w) => _shotJoints[(int)w];
        public GameObject VisualFor(WeaponType w) => _visualInstances[(int)w];
        public bool IsRigged(WeaponType w) => _animators[(int)w] != null;

        void Awake()
        {
            if (Controller == null) Controller = GetComponentInParent<WeaponController>();
            _player = GetComponentInParent<Player>();
            _audioSource = GetComponent<AudioSource>();
            if (_audioSource == null) _audioSource = gameObject.AddComponent<AudioSource>();
            _audioSource.playOnAwake = false;
            _audioSource.spatialBlend = 0f; // first-person weapon: 2D, not positional
            LoadVisuals();
            transform.localPosition = RestLocalPosition;
            transform.localRotation = Quaternion.Euler(RestLocalEulerAngles);
        }

        void OnEnable()
        {
            if (Controller != null) Controller.WeaponChanged += OnWeaponChanged;
        }

        void OnDisable()
        {
            if (Controller != null) Controller.WeaponChanged -= OnWeaponChanged;
        }

        void OnWeaponChanged(WeaponType previous, WeaponType current)
        {
            _switchTimer = SwitchDuration;
            var clip = WeaponAudio.Common("weapon_switch");
            if (clip != null && _audioSource != null) _audioSource.PlayOneShot(clip, 0.7f);
            var anim = _animators[(int)current];
            if (anim != null) anim.Play("idle", true);
        }

        void LoadVisuals()
        {
            for (int i = 0; i < WeaponController.WeaponCount; i++)
            {
                var type = (WeaponType)i;
                string resource = "Weapons/" + type + "WeaponVisual";
                var prefab = Resources.Load<GameObject>(resource);
                GameObject visual = null;
                if (prefab == null)
                {
                    Debug.LogWarning("[WeaponView] Missing generated prefab \"" + resource +
                        "\". Run MyXonotic/Import/Generate Weapon Visuals in the Editor first.");
                }
                else
                {
                    visual = Instantiate(prefab, transform);
                    visual.SetActive(false);
                    _visualInstances[i] = visual;
                }

                var info = Resources.Load<WeaponRigInfo>("Weapons/" + type + "WeaponRig");
                if (info == null || info.Rig == null || info.Rig.JointCount == 0) continue;
                _rigInfos[i] = info;
                var root = new GameObject("Rig_" + type);
                root.transform.SetParent(transform, false);
                // Converted source +X must point along camera +Z (same rule as the static prefab).
                root.transform.localRotation = Quaternion.Euler(0f, -90f, 0f);
                var anim = CharacterAnimator.Create(root.transform, info.Rig, info.SkinnedMesh, info.Materials);
                anim.Play("idle", true);
                if (!info.HasOwnMesh && info.WeaponJoint >= 0 && info.WeaponJoint < anim.Bones.Length && visual != null)
                {
                    // Xonotic: setattachment(v_ model, viewmodel, "weapon") — no extra offset.
                    visual.transform.SetParent(anim.Bones[info.WeaponJoint], false);
                    visual.transform.localPosition = Vector3.zero;
                    visual.transform.localRotation = Quaternion.identity;
                    visual.transform.localScale = Vector3.one;
                    visual.SetActive(true);
                }
                else if (visual != null)
                {
                    visual.SetActive(false); // DPM rig renders the whole gun itself
                }
                if (info.ShotJoint >= 0 && info.ShotJoint < anim.Bones.Length) _shotJoints[i] = anim.Bones[info.ShotJoint];
                root.SetActive(false);
                _rigRoots[i] = root;
                _animators[i] = anim;
            }
        }

        void Update()
        {
            if (Controller != null) RefreshVisibility(Controller.Current);
            if (ArenaBootstrap.IsPaused) return;

            float dt = Time.deltaTime;
            float t = 1f - Mathf.Exp(-KickRecoverySpeed * dt);
            _kickOffset = Vector3.Lerp(_kickOffset, Vector3.zero, t);
            _kickPitch = Mathf.Lerp(_kickPitch, 0f, t);

            // Switch: weapon rises from below over SwitchDuration.
            float drop = 0f;
            if (_switchTimer > 0f)
            {
                _switchTimer -= dt;
                float k = Mathf.Clamp01(_switchTimer / SwitchDuration);
                drop = SwitchDropDistance * k * k;
            }

            // Walk bob from the player's horizontal speed.
            Vector3 bob = Vector3.zero;
            if (_player != null && _player.IsGrounded)
            {
                var v = _player.Velocity; v.y = 0f;
                float speed01 = Mathf.Clamp01(v.magnitude / Player.WalkSpeed);
                float phase = Time.time * 9f;
                bob = new Vector3(Mathf.Sin(phase) * 0.012f, -Mathf.Abs(Mathf.Cos(phase)) * 0.01f, 0f) * speed01;
            }

            bool rigged = Controller != null && IsRigged(Controller.Current);
            Vector3 rest = rigged ? RigRestLocalPosition : RestLocalPosition;
            transform.localPosition = rest + _kickOffset + bob + Vector3.down * drop;
            transform.localRotation = Quaternion.Euler(RestLocalEulerAngles + new Vector3(-_kickPitch + drop * 40f, 0f, 0f));

            // Finished one-shot clips (fire/fire2/reload) settle back into idle.
            if (rigged)
            {
                var anim = _animators[(int)Controller.Current];
                if (anim.IsFinished && anim.CurrentClip != "idle") anim.Play("idle", true);
            }
        }

        void RefreshVisibility(WeaponType current)
        {
            if (current == _shownWeapon) return;
            for (int i = 0; i < WeaponController.WeaponCount; i++)
            {
                bool show = i == (int)current;
                if (_rigRoots[i] != null) _rigRoots[i].SetActive(show);
                else if (_visualInstances[i] != null) _visualInstances[i].SetActive(show);
            }
            _shownWeapon = current;
        }

        /// <summary>Recoil after a successful shot: original fire clip when rigged, plus a (smaller) procedural kick.</summary>
        public void Kick(bool alt = false)
        {
            float heavy = Controller != null && Controller.CurrentDef.Primary.SplashRadius > 2f ? 1.8f : 1f;
            bool rigged = Controller != null && IsRigged(Controller.Current);
            float scale = rigged ? 0.45f : 1f;
            _kickOffset = new Vector3(0f, 0f, -KickBackDistance * heavy * scale);
            _kickPitch = KickPitchDegrees * heavy * scale;
            PlayFireAnimation(alt);
        }

        /// <summary>Plays the rig's fire (or fire2) clip and a muzzle flash at the shot joint.</summary>
        public void PlayFireAnimation(bool alt)
        {
            if (Controller == null) return;
            int i = (int)Controller.Current;
            var anim = _animators[i];
            if (anim != null)
            {
                if (!(alt && anim.Play("fire2", true))) anim.Play("fire", true);
            }
            var shot = _shotJoints[i];
            if (shot != null) ImpactEffects.MuzzleFlash(shot, Controller.CurrentDef.Tint);
        }

        /// <summary>Plays the current weapon's original fire (or alt-fire) sound.</summary>
        public void PlayFireSound(bool alt = false)
        {
            if (_audioSource == null || Controller == null) return;
            var clip = WeaponAudio.Fire(Controller.Current, alt);
            if (clip != null) _audioSource.PlayOneShot(clip);
        }
    }
}
