using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace MyXonotic.EditorTools
{
    /// <summary>
    /// dev.11: imports Xonotic's animated first-person weapon models
    /// (<c>models/weapons/h_&lt;name&gt;.iqm</c>) into <see cref="WeaponRigInfo"/>
    /// assets under <c>Assets/MyXonotic/Resources/Weapons</c>.
    ///
    /// Two source flavours exist in 0.8.6 data:
    /// <list type="bullet">
    /// <item>Skeleton-only IQM (laser, shotgun, uzi, nex, campingrifle, minelayer,
    /// arc, fireball, hookgun): joints origin → weapon → shot/shell, a 4-vertex
    /// <c>nodraw</c> plane, clips fire/fire2/idle/reload. The static <c>v_</c>
    /// visual generated by <see cref="IqmWeaponImporter"/> is attached to the
    /// <c>weapon</c> joint at runtime (what Xonotic's <c>setattachment(…, "weapon")</c> does).</item>
    /// <item>DarkPlaces DPM (electro, crylink, gl, hagar, rl): the whole gun as a
    /// skinned mesh with <c>tag_handle/tag_shot/tag_shell</c> bones; clips come
    /// from the <c>.framegroups</c> file. Imported as a SkinnedMeshRenderer mesh.</item>
    /// </list>
    /// Runs inside <see cref="IqmWeaponImporter.GenerateWeaponAssets"/>; failures
    /// are recorded per weapon and never abort the build (the weapon then keeps
    /// the static dev.8 visual).
    /// </summary>
    public static class WeaponRigImporter
    {
        public const string ResourcesRoot = "Assets/MyXonotic/Resources/Weapons";
        public const string GeneratedRoot = "Assets/MyXonotic/Generated/Weapons";
        const string ShaderName = "MyXonotic/Lightmapped";

        /// <summary>Xonotic clip order shared by every h_ model (WFRAME_FIRE1, FIRE2, IDLE, RELOAD).</summary>
        public static readonly string[] ClipNames = { "fire", "fire2", "idle", "reload" };

        static readonly Dictionary<WeaponType, string> Sources = new Dictionary<WeaponType, string>
        {
            [WeaponType.Blaster] = "laser", [WeaponType.Shotgun] = "shotgun", [WeaponType.MachineGun] = "uzi",
            [WeaponType.Mortar] = "gl", [WeaponType.Electro] = "electro", [WeaponType.Crylink] = "crylink",
            [WeaponType.Vortex] = "nex", [WeaponType.Hagar] = "hagar", [WeaponType.Devastator] = "rl",
            [WeaponType.Rifle] = "campingrifle", [WeaponType.Minelayer] = "minelayer", [WeaponType.Arc] = "arc",
            [WeaponType.Fireball] = "fireball", [WeaponType.Hook] = "hookgun"
        };

        public sealed class Result
        {
            public string WeaponName;
            public string SourcePath;
            public string Format;
            public bool Ok;
            public string Error;
            public int Joints, Frames, Clips, Vertices;
            public bool OwnMesh;
            public readonly List<string> Notes = new List<string>();
        }

        public static string SourceName(WeaponType type) => Sources.TryGetValue(type, out var n) ? n : null;

        public static List<Result> ImportAll(XonoticContentResolver resolver)
        {
            var results = new List<Result>();
            for (int i = 0; i < WeaponController.WeaponCount; i++)
                results.Add(ImportOne((WeaponType)i, resolver));
            AssetDatabase.SaveAssets();
            return results;
        }

        public static Result ImportOne(WeaponType type, XonoticContentResolver resolver)
        {
            var result = new Result { WeaponName = type.ToString() };
            string rel = "models/weapons/h_" + SourceName(type) + ".iqm";
            string path = null;
            foreach (var root in resolver.Roots)
            {
                var candidate = Path.Combine(root, rel);
                if (File.Exists(candidate)) { path = candidate; break; }
            }
            result.SourcePath = path;
            if (path == null) { result.Error = rel + " not found in content roots."; return result; }
            try
            {
                byte[] data = File.ReadAllBytes(path);
                var groups = IqmCharacterImporter.ReadFrameGroups(path + ".framegroups");
                var info = ScriptableObject.CreateInstance<WeaponRigInfo>();
                info.WeaponName = type.ToString();
                if (DpmDocument.IsDpm(data))
                {
                    result.Format = "DPM";
                    ImportDpm(type, data, path, groups, resolver, info, result);
                }
                else
                {
                    result.Format = "IQM";
                    ImportIqm(type, data, path, groups, info, result);
                }
                info.SourceFormat = result.Format;
                info.Rig = IqmCharacterImporter.Persist(info.Rig, ResourcesRoot + "/" + type + "Hands_Rig.asset");
                if (info.SkinnedMesh != null)
                    info.SkinnedMesh = IqmCharacterImporter.Persist(info.SkinnedMesh, ResourcesRoot + "/" + type + "Hands_Skinned.asset");
                IqmCharacterImporter.Persist(info, ResourcesRoot + "/" + type + "WeaponRig.asset");
                result.Joints = info.Rig.JointCount;
                result.Frames = info.Rig.FrameCount;
                result.Clips = info.Rig.Clips.Length;
                result.OwnMesh = info.SkinnedMesh != null;
                result.Ok = true;
            }
            catch (Exception e)
            {
                result.Error = e.Message;
                // Remove a stale asset so the runtime falls back to the static visual.
                AssetDatabase.DeleteAsset(ResourcesRoot + "/" + type + "WeaponRig.asset");
            }
            return result;
        }

        // ---------------------------------------------------------------- IQM

        static void ImportIqm(WeaponType type, byte[] data, string path, List<IqmCharacterImporter.FrameGroup> groups,
            WeaponRigInfo info, Result result)
        {
            var doc = IqmSkinnedDocument.Read(data, path);
            int n = doc.JointCount;
            if (n == 0) throw new InvalidDataException("h_ model has no joints: " + path);
            var rig = ScriptableObject.CreateInstance<CharacterRig>();
            rig.ModelName = type + "Hands";
            rig.JointNames = new string[n];
            rig.JointParents = new int[n];
            rig.BindLocal = new float[n * 10];
            for (int j = 0; j < n; j++)
            {
                doc.GetJoint(j, out rig.JointNames[j], out rig.JointParents[j], out Vector3 t, out Quaternion r, out Vector3 s);
                IqmCharacterImporter.WriteTrs(rig.BindLocal, j * 10, IqmCharacterImporter.ToUnityT(t), IqmCharacterImporter.ToUnityQ(r), IqmCharacterImporter.ToUnityS(s));
            }
            int frames = doc.FrameCount;
            rig.FrameCount = frames;
            rig.Poses = new float[frames * n * 10];
            for (int f = 0; f < frames; f++)
                for (int j = 0; j < n; j++)
                {
                    doc.GetFramePose(f, j, out Vector3 t, out Quaternion r, out Vector3 s);
                    IqmCharacterImporter.WriteTrs(rig.Poses, (f * n + j) * 10, IqmCharacterImporter.ToUnityT(t), IqmCharacterImporter.ToUnityQ(r), IqmCharacterImporter.ToUnityS(s));
                }
            var clips = new List<CharacterRig.Clip>();
            for (int a = 0; a < doc.AnimCount; a++)
            {
                doc.GetAnim(a, out string aname, out int first, out int count, out float rate, out bool loop);
                string name = a < ClipNames.Length ? ClipNames[a] : aname;
                if (groups != null && a < groups.Count) { rate = groups[a].Fps; loop = groups[a].Loop; }
                if (rate <= 0f) rate = 20f;
                if (a < ClipNames.Length) loop = a == 2; // only idle loops; fire/fire2/reload are one-shots
                clips.Add(new CharacterRig.Clip { Name = name, FirstFrame = first, FrameCount = Mathf.Max(1, Mathf.Min(count, frames - first)), FramesPerSecond = rate, Loop = loop });
            }
            if (clips.Count == 0) throw new InvalidDataException("h_ model has no animations: " + path);
            rig.Clips = clips.ToArray();
            info.Rig = rig;
            info.WeaponJoint = IndexOf(rig.JointNames, "weapon");
            info.ShotJoint = IndexOf(rig.JointNames, "shot", "tag_shot");
            info.HandleJoint = IndexOf(rig.JointNames, "tag_handle", "origin");
            if (info.WeaponJoint < 0) throw new InvalidDataException("IQM h_ model has no 'weapon' joint: " + path);
            result.Notes.Add(string.Format("IQM skeleton {0} joints, {1} frames, clips {2}; v_ visual attaches to joint '{3}'.",
                n, frames, string.Join("/", clips.ConvertAll(c => c.Name + ":" + c.FrameCount + "@" + c.FramesPerSecond)), rig.JointNames[info.WeaponJoint]));
        }

        // ---------------------------------------------------------------- DPM

        static void ImportDpm(WeaponType type, byte[] data, string path, List<IqmCharacterImporter.FrameGroup> groups,
            XonoticContentResolver resolver, WeaponRigInfo info, Result result)
        {
            var doc = DpmDocument.Read(data, path);
            int n = doc.BoneCount;
            var rig = ScriptableObject.CreateInstance<CharacterRig>();
            rig.ModelName = type + "Hands";
            rig.JointNames = new string[n];
            rig.JointParents = new int[n];
            rig.BindLocal = new float[n * 10];
            for (int j = 0; j < n; j++)
            {
                rig.JointNames[j] = doc.Bones[j].Name;
                rig.JointParents[j] = doc.Bones[j].Parent;
                DpmDocument.Decompose(doc.Frames[0].Local[j], out Vector3 t, out Quaternion r, out Vector3 s);
                IqmCharacterImporter.WriteTrs(rig.BindLocal, j * 10, IqmCharacterImporter.ToUnityT(t), IqmCharacterImporter.ToUnityQ(r), IqmCharacterImporter.ToUnityS(s));
            }
            int frames = doc.FrameCount;
            rig.FrameCount = frames;
            rig.Poses = new float[frames * n * 10];
            for (int f = 0; f < frames; f++)
                for (int j = 0; j < n; j++)
                {
                    DpmDocument.Decompose(doc.Frames[f].Local[j], out Vector3 t, out Quaternion r, out Vector3 s);
                    IqmCharacterImporter.WriteTrs(rig.Poses, (f * n + j) * 10, IqmCharacterImporter.ToUnityT(t), IqmCharacterImporter.ToUnityQ(r), IqmCharacterImporter.ToUnityS(s));
                }
            if (groups == null || groups.Count == 0) throw new InvalidDataException("DPM h_ model needs a .framegroups file: " + path);
            var clips = new List<CharacterRig.Clip>();
            for (int a = 0; a < groups.Count; a++)
            {
                var g = groups[a];
                int first = Mathf.Clamp(g.First, 0, frames - 1);
                int count = Mathf.Max(1, Mathf.Min(g.Count, frames - first));
                clips.Add(new CharacterRig.Clip { Name = a < ClipNames.Length ? ClipNames[a] : "clip" + a, FirstFrame = first, FrameCount = count, FramesPerSecond = g.Fps > 0f ? g.Fps : 20f, Loop = a < ClipNames.Length ? a == 2 : g.Loop });
            }
            rig.Clips = clips.ToArray();
            info.Rig = rig;
            info.ShotJoint = IndexOf(rig.JointNames, "tag_shot", "shot");
            info.HandleJoint = IndexOf(rig.JointNames, "tag_handle");
            info.WeaponJoint = -1; // the DPM carries the whole gun; no v_ attachment

            // Skinned mesh: bind pose = frame 0, one submesh per DPM mesh, materials
            // resolved through the same shader-script path as the static weapons.
            var surfaces = new MyXonotic.Content.Md3.Md3Surface[doc.Meshes.Length];
            var positions = new List<Vector3>();
            var normals = new List<Vector3>();
            var uvs = new List<Vector2>();
            var weights = new List<BoneWeight>();
            var submeshes = new int[doc.Meshes.Length][];
            int vertexBase = 0;
            for (int m = 0; m < doc.Meshes.Length; m++)
            {
                doc.SkinMesh(m, 0, out Vector3[] rawPos, out Vector3[] rawNrm);
                var mesh = doc.Meshes[m];
                var surf = new MyXonotic.Content.Md3.Md3Surface
                {
                    Name = mesh.ShaderName,
                    ShaderNames = new[] { mesh.ShaderName },
                    Positions = new MyXonotic.Content.Bsp.BspVec3[rawPos.Length],
                    Normals = new MyXonotic.Content.Bsp.BspVec3[rawPos.Length],
                    TexCoords = new MyXonotic.Content.Bsp.BspVec2[rawPos.Length],
                    Triangles = mesh.Triangles
                };
                for (int v = 0; v < rawPos.Length; v++)
                {
                    var p = IqmCharacterImporter.ToUnityT(rawPos[v]);
                    var nr = new Vector3(rawNrm[v].x, rawNrm[v].z, rawNrm[v].y);
                    positions.Add(p); normals.Add(nr); uvs.Add(mesh.TexCoords[v]);
                    surf.Positions[v] = new MyXonotic.Content.Bsp.BspVec3(p.x, p.y, p.z);
                    surf.Normals[v] = new MyXonotic.Content.Bsp.BspVec3(nr.x, nr.y, nr.z);
                    surf.TexCoords[v] = new MyXonotic.Content.Bsp.BspVec2(mesh.TexCoords[v].x, mesh.TexCoords[v].y);
                }
                weights.AddRange(doc.BuildBoneWeights(m));
                var tris = new int[mesh.Triangles.Length];
                for (int i = 0; i < tris.Length; i++) tris[i] = mesh.Triangles[i] + vertexBase;
                submeshes[m] = tris;
                vertexBase += rawPos.Length;
                surfaces[m] = surf;
            }
            var asMd3 = new MyXonotic.Content.Md3.Md3StaticModel { Name = type + "Hands", Surfaces = surfaces };
            Directory.CreateDirectory(GeneratedRoot);
            var built = Md3WeaponModelBuilder.Build(asMd3, resolver, type + "Hands", GeneratedRoot, ShaderName);
            result.Notes.AddRange(built.Notes);

            var skinned = new Mesh { name = type + "Hands_Skinned" };
            if (positions.Count > 65535) skinned.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
            skinned.SetVertices(positions);
            skinned.SetNormals(normals);
            skinned.SetUVs(0, uvs);
            skinned.subMeshCount = doc.Meshes.Length;
            for (int m = 0; m < doc.Meshes.Length; m++) skinned.SetTriangles(submeshes[m], m);
            skinned.boneWeights = weights.ToArray();
            var world = new Matrix4x4[n];
            var bindposes = new Matrix4x4[n];
            for (int j = 0; j < n; j++)
            {
                rig.GetBind(j, out Vector3 t, out Quaternion r, out Vector3 s);
                var local = Matrix4x4.TRS(t, r.normalized, s);
                int p = rig.JointParents[j];
                world[j] = p >= 0 ? world[p] * local : local;
                bindposes[j] = world[j].inverse;
            }
            skinned.bindposes = bindposes;
            skinned.RecalculateBounds();
            info.SkinnedMesh = skinned;
            info.Materials = built.Materials;
            result.Vertices = positions.Count;
            result.Notes.Add(string.Format("DPM {0} bones, {1} frames, {2} verts, clips {3}; muzzle joint '{4}'.",
                n, frames, positions.Count, string.Join("/", clips.ConvertAll(c => c.Name + ":" + c.FrameCount + "@" + c.FramesPerSecond)),
                info.ShotJoint >= 0 ? rig.JointNames[info.ShotJoint] : "(none)"));
        }

        static int IndexOf(string[] names, params string[] wanted)
        {
            foreach (var w in wanted)
                for (int i = 0; i < names.Length; i++)
                    if (string.Equals(names[i], w, StringComparison.OrdinalIgnoreCase)) return i;
            return -1;
        }
    }
}
