using System.Collections.Generic;
using MyXonotic.Content;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace MyXonotic.Menu
{
    public enum MenuScreen { Home = 0, Play = 1, Settings = 2 }

    /// <summary>
    /// Runtime-built main menu (dev.13 rewrite). Three screens under one canvas,
    /// created entirely in code like the HUD (no prefabs):
    ///  - HOME: original luminos menu background (when generated by HudArtImporter),
    ///    title, three big thumb-sized buttons PLAY / SETTINGS / QUIT, a featured
    ///    map preview and the version line.
    ///  - PLAY: mode row (DM / TDM / CTF with the original gametype icons), ALL
    ///    WEAPONS toggle, BOTS - n +, and the map grid filtered to maps whose
    ///    .mapinfo lists the chosen gametype (SHOW ALL lifts the filter).
    ///  - SETTINGS: touch controls (button size, look sensitivity, invert Y,
    ///    left-handed) via TouchSettings, plus the DevCapture report buttons.
    /// Layout rules from dev.10/dev.12 still apply: positive rects everywhere,
    /// RectMask2D not Mask, anchor-pivoted edges. LocalTests.MainMenuGeometry
    /// builds every screen headlessly and checks the geometry.
    /// </summary>
    public sealed class MainMenu : MonoBehaviour
    {
        static readonly Color Background = new Color32(14, 16, 22, 255);
        static readonly Color CardColor = new Color32(30, 34, 46, 235);
        static readonly Color CardPressed = new Color32(60, 70, 96, 255);
        static readonly Color Accent = new Color32(255, 140, 40, 255);
        static readonly Color AccentDark = new Color32(190, 95, 20, 255);
        static readonly Color TextColor = new Color32(235, 235, 240, 255);
        static readonly Color SubText = new Color32(170, 175, 190, 255);
        static readonly Color PanelColor = new Color32(0, 36, 64, 150); // luma panel blue, translucent

        /// Min touch target height in reference (1280x720) pixels.
        const float ButtonH = 60f;

        Font _font;
        MapCatalog _catalog;
        RectTransform _safe;
        readonly Dictionary<MenuScreen, GameObject> _screens = new Dictionary<MenuScreen, GameObject>();
        public MenuScreen Current { get; private set; } = MenuScreen.Home;

        void Start()
        {
            Application.targetFrameRate = 60;
            Screen.sleepTimeout = SleepTimeout.SystemSetting;
            Cursor.lockState = CursorLockMode.None;
            Cursor.visible = true;
            _font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            _catalog = MapCatalog.Load();
            // dev.16: Firebase Test Lab Game Loop starts a match without a human.
            if (GameLoop.LaunchFromMenu(_catalog)) return;
            Build();
        }

        void Build()
        {
            if (FindObjectOfType<EventSystem>() == null)
            {
                var es = new GameObject("EventSystem", typeof(EventSystem), typeof(StandaloneInputModule));
                es.transform.SetParent(transform, false);
                es.GetComponent<EventSystem>().sendNavigationEvents = false;
            }
            var cam = new GameObject("MenuCamera", typeof(Camera));
            cam.transform.SetParent(transform, false);
            var camera = cam.GetComponent<Camera>();
            camera.clearFlags = CameraClearFlags.SolidColor;
            camera.backgroundColor = Background;
            camera.cullingMask = 0;

            var canvasGO = new GameObject("MenuCanvas");
            canvasGO.transform.SetParent(transform, false);
            var canvas = canvasGO.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            var scaler = canvasGO.AddComponent<CanvasScaler>();
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            scaler.referenceResolution = new Vector2(1280, 720);
            scaler.matchWidthOrHeight = 0.5f;
            canvasGO.AddComponent<GraphicRaycaster>();

            var bg = MakeImage("Background", canvasGO.transform, Background);
            Stretch(bg.rectTransform, Vector2.zero, Vector2.zero);
            var art = HudArt.Sprite("menu_background");
            if (art != null)
            {
                bg.sprite = art;
                bg.color = new Color(0.75f, 0.8f, 0.9f, 1f); // slightly dimmed so text stays readable
                bg.preserveAspect = false;
            }
            var shade = MakeImage("Shade", canvasGO.transform, new Color(0f, 0f, 0f, 0.35f));
            Stretch(shade.rectTransform, Vector2.zero, Vector2.zero);

            _safe = new GameObject("SafeArea", typeof(RectTransform)).GetComponent<RectTransform>();
            _safe.SetParent(canvasGO.transform, false);
            Stretch(_safe, Vector2.zero, Vector2.zero);
            ApplySafeArea(_safe);

            _screens[MenuScreen.Home] = BuildHome();
            _screens[MenuScreen.Play] = BuildPlay();
            _screens[MenuScreen.Settings] = BuildSettings();
            ShowScreen(MenuScreen.Home);
        }

        /// Switch screens (also used by the Editor geometry test).
        public void ShowScreen(MenuScreen screen)
        {
            Current = screen;
            foreach (var kv in _screens) kv.Value.SetActive(kv.Key == screen);
            if (screen == MenuScreen.Play) RefreshOptions();
            if (screen == MenuScreen.Settings) RefreshSettings();
        }

        RectTransform NewScreen(string name)
        {
            var rt = new GameObject(name, typeof(RectTransform)).GetComponent<RectTransform>();
            rt.SetParent(_safe, false);
            Stretch(rt, Vector2.zero, Vector2.zero);
            return rt;
        }

        // ------------------------------------------------------------ HOME

        GameObject BuildHome()
        {
            var screen = NewScreen("Home");
            int count = _catalog != null ? _catalog.maps.Count : 0;
            string version = _catalog != null && !string.IsNullOrEmpty(_catalog.buildVersion) ? _catalog.buildVersion : Application.version;

            var title = MakeText("Title", screen, "MY XONOTIC", 56, TextAnchor.MiddleLeft, Accent, FontStyle.Bold);
            SetRect(title.rectTransform, new Vector2(0f, 1f), new Vector2(0.6f, 1f), new Vector2(0f, 1f), new Vector2(40f, -110f), new Vector2(0f, -30f));
            var sub = MakeText("Subtitle", screen,
                count + " maps · Unity reimplementation " + version + " · original Xonotic art (GPL) · development build",
                15, TextAnchor.MiddleLeft, SubText, FontStyle.Normal);
            SetRect(sub.rectTransform, new Vector2(0f, 1f), new Vector2(0.62f, 1f), new Vector2(0f, 1f), new Vector2(40f, -140f), new Vector2(0f, -112f));

            // Left column of big buttons.
            float y = -190f;
            var play = MakeButton("Play", screen, "PLAY", () => ShowScreen(MenuScreen.Play));
            play.GetComponent<Image>().color = Accent;
            SetRect(play.GetComponent<RectTransform>(), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(40f, y - 78f), new Vector2(360f, y));
            play.GetComponentInChildren<Text>().fontSize = 30;
            y -= 96f;
            var settings = MakeButton("Settings", screen, "SETTINGS", () => ShowScreen(MenuScreen.Settings));
            SetRect(settings.GetComponent<RectTransform>(), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(40f, y - ButtonH), new Vector2(360f, y));
            y -= ButtonH + 18f;
            var quit = MakeButton("Quit", screen, "QUIT", () => Application.Quit());
            SetRect(quit.GetComponent<RectTransform>(), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(40f, y - ButtonH), new Vector2(360f, y));

            // Featured map card on the right: a preview so the home screen is not text-only.
            var card = MakeImage("Featured", screen, PanelColor);
            SetRect(card.rectTransform, new Vector2(1f, 1f), new Vector2(1f, 1f), new Vector2(1f, 1f), new Vector2(-560f, -430f), new Vector2(-40f, -160f));
            MapCatalog.Entry featured = null;
            if (_catalog != null && _catalog.maps.Count > 0)
                featured = _catalog.maps[Application.isBatchMode ? 0 : Random.Range(0, _catalog.maps.Count)];
            var preview = MakeImage("FeaturedPreview", card.transform, new Color32(50, 55, 70, 255));
            SetRect(preview.rectTransform, Vector2.zero, Vector2.one, new Vector2(0.5f, 0.5f), new Vector2(8f, 44f), new Vector2(-8f, -8f));
            if (featured != null && featured.preview != null)
            {
                preview.sprite = Sprite.Create(featured.preview, new Rect(0, 0, featured.preview.width, featured.preview.height), new Vector2(0.5f, 0.5f));
                preview.color = Color.white;
            }
            var featuredText = MakeText("FeaturedTitle", card.transform,
                featured != null ? (string.IsNullOrEmpty(featured.title) ? featured.mapName : featured.title) + "  ·  " + (featured.author ?? "") : "No maps packaged",
                16, TextAnchor.MiddleLeft, TextColor, FontStyle.Bold);
            SetRect(featuredText.rectTransform, new Vector2(0f, 0f), new Vector2(1f, 0f), new Vector2(0f, 0f), new Vector2(12f, 6f), new Vector2(-12f, 40f));
            if (featured != null)
            {
                var b = card.gameObject.AddComponent<Button>();
                string scene = featured.sceneName;
                b.onClick.AddListener(() => SceneFlow.LoadMap(scene));
                card.raycastTarget = true;
            }

            var foot = MakeText("Footer", screen, "Unofficial Unity remake · not affiliated with Team Xonotic · maps, models, sounds and music © their authors (GPL)",
                12, TextAnchor.LowerLeft, SubText, FontStyle.Normal);
            SetRect(foot.rectTransform, new Vector2(0f, 0f), new Vector2(1f, 0f), new Vector2(0f, 0f), new Vector2(40f, 12f), new Vector2(-40f, 36f));
            return screen.gameObject;
        }

        // ------------------------------------------------------------ PLAY

        Text _modeLabels0, _modeLabels1, _modeLabels2, _allWeaponsLabel, _botsLabel, _botsMinus, _botsPlus, _showAllLabel, _mapCountText;
        Image _mode0, _mode1, _mode2, _allWeaponsImg, _showAllImg;
        RectTransform _gridContent;
        readonly List<GameObject> _cards = new List<GameObject>();
        bool _showAllMaps;

        GameObject BuildPlay()
        {
            var screen = NewScreen("Play");
            BuildHeader(screen, "PLAY");
            BuildMatchOptions(screen);

            // RectMask2D, not Mask (dev.10 lesson: a stencil Mask on an
            // alpha-0.001 Image hides every card on device).
            var scrollGO = new GameObject("MapScroll", typeof(RectTransform), typeof(Image), typeof(ScrollRect), typeof(RectMask2D));
            scrollGO.transform.SetParent(screen, false);
            var scrollRT = scrollGO.GetComponent<RectTransform>();
            SetRect(scrollRT, Vector2.zero, Vector2.one, new Vector2(0.5f, 0.5f), new Vector2(20f, 16f), new Vector2(-20f, -150f));
            scrollGO.GetComponent<Image>().color = new Color(0, 0, 0, 0f); // raycast target only
            var scroll = scrollGO.GetComponent<ScrollRect>();
            scroll.horizontal = false;
            scroll.vertical = true;
            scroll.movementType = ScrollRect.MovementType.Elastic;
            scroll.scrollSensitivity = 30f;

            _gridContent = new GameObject("Content", typeof(RectTransform)).GetComponent<RectTransform>();
            _gridContent.SetParent(scrollGO.transform, false);
            _gridContent.anchorMin = new Vector2(0f, 1f);
            _gridContent.anchorMax = new Vector2(1f, 1f);
            _gridContent.pivot = new Vector2(0.5f, 1f);
            _gridContent.anchoredPosition = Vector2.zero;
            _gridContent.sizeDelta = Vector2.zero;
            var grid = _gridContent.gameObject.AddComponent<GridLayoutGroup>();
            grid.cellSize = new Vector2(290f, 210f);
            grid.spacing = new Vector2(16f, 16f);
            grid.padding = new RectOffset(10, 10, 10, 10);
            grid.childAlignment = TextAnchor.UpperCenter;
            grid.constraint = GridLayoutGroup.Constraint.Flexible;
            var fitter = _gridContent.gameObject.AddComponent<ContentSizeFitter>();
            fitter.verticalFit = ContentSizeFitter.FitMode.PreferredSize;
            scroll.content = _gridContent;
            scroll.viewport = scrollRT;

            if (_catalog == null || _catalog.maps.Count == 0)
            {
                var none = MakeText("NoMaps", screen, "No maps were packaged in this build.", 24, TextAnchor.MiddleCenter, TextColor, FontStyle.Normal);
                Stretch(none.rectTransform, Vector2.zero, Vector2.zero);
                return screen.gameObject;
            }
            foreach (var entry in _catalog.maps) _cards.Add(BuildCard(_gridContent, entry));
            return screen.gameObject;
        }

        void BuildHeader(RectTransform screen, string caption)
        {
            var back = MakeButton("Back", screen, "‹  BACK", () => ShowScreen(MenuScreen.Home));
            SetRect(back.GetComponent<RectTransform>(), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(20f, -74f), new Vector2(160f, -16f));
            var title = MakeText("Caption", screen, caption, 30, TextAnchor.MiddleLeft, Accent, FontStyle.Bold);
            SetRect(title.rectTransform, new Vector2(0f, 1f), new Vector2(0.5f, 1f), new Vector2(0f, 1f), new Vector2(180f, -74f), new Vector2(0f, -16f));
        }

        /// One row: DM / TDM / CTF (with gametype icons), ALL WEAPONS, BOTS - n +, SHOW ALL.
        void BuildMatchOptions(RectTransform screen)
        {
            float y0 = -86f, y1 = -86f - 56f;
            _mode0 = OptionButton(screen, "ModeDM", 20f, 130f, y0, y1, out _modeLabels0, () => { MatchSettings.Mode = GameMode.Deathmatch; RefreshOptions(); }, HudArt.GametypeIconName(GameMode.Deathmatch));
            _mode1 = OptionButton(screen, "ModeTDM", 136f, 246f, y0, y1, out _modeLabels1, () => { MatchSettings.Mode = GameMode.TeamDeathmatch; RefreshOptions(); }, HudArt.GametypeIconName(GameMode.TeamDeathmatch));
            _mode2 = OptionButton(screen, "ModeCTF", 252f, 362f, y0, y1, out _modeLabels2, () => { MatchSettings.Mode = GameMode.CaptureTheFlag; RefreshOptions(); }, HudArt.GametypeIconName(GameMode.CaptureTheFlag));
            _allWeaponsImg = OptionButton(screen, "AllWeapons", 392f, 592f, y0, y1, out _allWeaponsLabel, () => { MatchSettings.AllWeapons = !MatchSettings.AllWeapons; RefreshOptions(); }, null);
            OptionButton(screen, "BotsMinus", 622f, 678f, y0, y1, out _botsMinus, () => { MatchSettings.BotCount = MatchSettings.BotCount - 1; RefreshOptions(); }, null);
            _botsLabel = MakeText("BotsLabel", screen, "", 18, TextAnchor.MiddleCenter, TextColor, FontStyle.Bold);
            SetRect(_botsLabel.rectTransform, new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(682f, y1), new Vector2(782f, y0));
            OptionButton(screen, "BotsPlus", 786f, 842f, y0, y1, out _botsPlus, () => { MatchSettings.BotCount = MatchSettings.BotCount + 1; RefreshOptions(); }, null);
            _showAllImg = OptionButton(screen, "ShowAll", 872f, 992f, y0, y1, out _showAllLabel, () => { _showAllMaps = !_showAllMaps; RefreshOptions(); }, null);
            _mapCountText = MakeText("MapCount", screen, "", 13, TextAnchor.MiddleRight, SubText, FontStyle.Normal);
            SetRect(_mapCountText.rectTransform, new Vector2(0f, 1f), new Vector2(1f, 1f), new Vector2(0f, 1f), new Vector2(1000f, y1), new Vector2(-20f, y0));
            RefreshOptions();
        }

        Image OptionButton(RectTransform parent, string name, float x0, float x1, float y0, float y1, out Text label, UnityEngine.Events.UnityAction onClick, string iconArt)
        {
            var go = MakeButton(name, parent, "", onClick);
            SetRect(go.GetComponent<RectTransform>(), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(x0, y1), new Vector2(x1, y0));
            label = go.GetComponentInChildren<Text>();
            label.fontSize = 17;
            var sprite = HudArt.Sprite(iconArt);
            if (sprite != null)
            {
                var icon = MakeImage("Icon", go.transform, Color.white);
                icon.sprite = sprite;
                icon.preserveAspect = true;
                SetRect(icon.rectTransform, new Vector2(0f, 0f), new Vector2(0f, 1f), new Vector2(0f, 0.5f), new Vector2(6f, 8f), new Vector2(46f, -8f));
                label.alignment = TextAnchor.MiddleRight;
                label.rectTransform.offsetMax = new Vector2(-10f, 0f);
            }
            return go.GetComponent<Image>();
        }

        static string GametypeKey(GameMode mode) => mode == GameMode.TeamDeathmatch ? "tdm" : mode == GameMode.CaptureTheFlag ? "ctf" : "dm";

        /// True when the map lists the gametype (or lists none at all).
        public static bool SupportsMode(MapCatalog.Entry entry, GameMode mode)
        {
            if (entry.gametypes == null || entry.gametypes.Length == 0) return true;
            string key = GametypeKey(mode);
            foreach (var g in entry.gametypes) if (g == key) return true;
            return false;
        }

        /// Number of catalog maps the PLAY grid shows for <paramref name="mode"/> (test helper).
        public static int VisibleMapCount(MapCatalog catalog, GameMode mode, bool showAll)
        {
            if (catalog == null) return 0;
            if (showAll) return catalog.maps.Count;
            int n = 0;
            foreach (var e in catalog.maps) if (SupportsMode(e, mode)) n++;
            return n;
        }

        void RefreshOptions()
        {
            if (_modeLabels0 == null) return;
            var mode = MatchSettings.Mode;
            _modeLabels0.text = "DM"; _modeLabels1.text = "TDM"; _modeLabels2.text = "CTF";
            _mode0.color = mode == GameMode.Deathmatch ? Accent : CardColor;
            _mode1.color = mode == GameMode.TeamDeathmatch ? Accent : CardColor;
            _mode2.color = mode == GameMode.CaptureTheFlag ? Accent : CardColor;
            _allWeaponsLabel.text = "ALL WEAPONS " + (MatchSettings.AllWeapons ? "ON" : "OFF");
            _allWeaponsImg.color = MatchSettings.AllWeapons ? Accent : CardColor;
            _botsLabel.text = "BOTS " + MatchSettings.BotCount;
            _botsMinus.text = "-"; _botsPlus.text = "+";
            _showAllLabel.text = _showAllMaps ? "ALL MAPS" : MatchSettings.ModeShort(mode) + " MAPS";
            _showAllImg.color = _showAllMaps ? AccentDark : CardColor;

            int shown = 0;
            if (_catalog != null)
                for (int i = 0; i < _cards.Count && i < _catalog.maps.Count; i++)
                {
                    bool visible = _showAllMaps || SupportsMode(_catalog.maps[i], mode);
                    _cards[i].SetActive(visible);
                    if (visible) shown++;
                }
            _mapCountText.text = _catalog != null ? shown + " / " + _catalog.maps.Count + " maps" : "";
            if (_gridContent != null) LayoutRebuilder.MarkLayoutForRebuild(_gridContent);
        }

        GameObject BuildCard(Transform parent, MapCatalog.Entry entry)
        {
            var card = new GameObject("Card_" + entry.mapName, typeof(RectTransform), typeof(Image), typeof(Button));
            card.transform.SetParent(parent, false);
            var img = card.GetComponent<Image>();
            img.color = CardColor;
            var button = card.GetComponent<Button>();
            var colors = button.colors;
            colors.normalColor = CardColor;
            colors.highlightedColor = CardPressed;
            colors.pressedColor = CardPressed;
            colors.selectedColor = CardColor;
            button.colors = colors;
            string scene = entry.sceneName;
            button.onClick.AddListener(() => SceneFlow.LoadMap(scene));

            var preview = MakeImage("Preview", card.transform, Color.white);
            SetRect(preview.rectTransform, new Vector2(0f, 1f), new Vector2(1f, 1f), new Vector2(0.5f, 1f), new Vector2(6f, -150f), new Vector2(-6f, -6f));
            if (entry.preview != null)
            {
                preview.sprite = Sprite.Create(entry.preview, new Rect(0, 0, entry.preview.width, entry.preview.height), new Vector2(0.5f, 0.5f));
                preview.preserveAspect = false;
            }
            else preview.color = new Color32(50, 55, 70, 255);

            var titleText = MakeText("Title", card.transform, string.IsNullOrEmpty(entry.title) ? entry.mapName : entry.title,
                20, TextAnchor.MiddleLeft, TextColor, FontStyle.Bold);
            SetRect(titleText.rectTransform, new Vector2(0f, 0f), new Vector2(1f, 0f), new Vector2(0f, 0f), new Vector2(10f, 30f), new Vector2(-10f, 58f));
            string meta = string.IsNullOrEmpty(entry.author) ? entry.mapName : entry.author;
            if (entry.gametypes != null && entry.gametypes.Length > 0)
                meta += "  ·  " + string.Join(" ", entry.gametypes).ToUpperInvariant();
            var metaText = MakeText("Meta", card.transform, meta, 12, TextAnchor.MiddleLeft, SubText, FontStyle.Normal);
            SetRect(metaText.rectTransform, new Vector2(0f, 0f), new Vector2(1f, 0f), new Vector2(0f, 0f), new Vector2(10f, 6f), new Vector2(-10f, 30f));
            return card;
        }

        // ------------------------------------------------------------ SETTINGS

        Text _scaleValue, _sensValue, _invertLabel, _leftLabel, _devSummary;
        Image _invertImg, _leftImg;

        GameObject BuildSettings()
        {
            var screen = NewScreen("Settings");
            BuildHeader(screen, "SETTINGS");

            var panel = MakeImage("TouchPanel", screen, PanelColor);
            SetRect(panel.rectTransform, new Vector2(0f, 1f), new Vector2(0.49f, 1f), new Vector2(0f, 1f), new Vector2(20f, -420f), new Vector2(-8f, -90f));
            var heading = MakeText("TouchHeading", panel.transform, "TOUCH CONTROLS", 18, TextAnchor.MiddleLeft, Accent, FontStyle.Bold);
            SetRect(heading.rectTransform, new Vector2(0f, 1f), new Vector2(1f, 1f), new Vector2(0f, 1f), new Vector2(16f, -44f), new Vector2(-16f, -8f));

            float y = -56f;
            _scaleValue = StepperRow(panel.rectTransform, "ButtonScale", "BUTTON SIZE", y,
                () => { TouchSettings.ButtonScale -= TouchSettings.ButtonScaleStep; RefreshSettings(); },
                () => { TouchSettings.ButtonScale += TouchSettings.ButtonScaleStep; RefreshSettings(); });
            y -= 70f;
            _sensValue = StepperRow(panel.rectTransform, "Sensitivity", "LOOK SENSITIVITY", y,
                () => { TouchSettings.Sensitivity -= TouchSettings.SensitivityStep; RefreshSettings(); },
                () => { TouchSettings.Sensitivity += TouchSettings.SensitivityStep; RefreshSettings(); });
            y -= 70f;
            _invertImg = ToggleRow(panel.rectTransform, "InvertY", "INVERT LOOK (Y)", y, out _invertLabel, () => { TouchSettings.InvertY = !TouchSettings.InvertY; RefreshSettings(); });
            y -= 70f;
            _leftImg = ToggleRow(panel.rectTransform, "LeftHanded", "LEFT-HANDED LAYOUT", y, out _leftLabel, () => { TouchSettings.LeftHanded = !TouchSettings.LeftHanded; RefreshSettings(); });
            y -= 70f;
            var reset = MakeButton("ResetTouch", panel.transform, "RESET DEFAULTS", () => { TouchSettings.ResetToDefaults(); RefreshSettings(); });
            SetRect(reset.GetComponent<RectTransform>(), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(16f, y - 48f), new Vector2(256f, y));
            reset.GetComponentInChildren<Text>().fontSize = 15;

            // DevCapture panel: what the phone recorded, and two ways to hand it over.
            var dev = MakeImage("DevPanel", screen, PanelColor);
            SetRect(dev.rectTransform, new Vector2(0.51f, 1f), new Vector2(1f, 1f), new Vector2(1f, 1f), new Vector2(8f, -420f), new Vector2(-20f, -90f));
            var devHeading = MakeText("DevHeading", dev.transform, "DEVCAPTURE — DEVICE REPORT", 18, TextAnchor.MiddleLeft, Accent, FontStyle.Bold);
            SetRect(devHeading.rectTransform, new Vector2(0f, 1f), new Vector2(1f, 1f), new Vector2(0f, 1f), new Vector2(16f, -44f), new Vector2(-16f, -8f));
            _devSummary = MakeText("DevSummary", dev.transform, "", 13, TextAnchor.UpperLeft, TextColor, FontStyle.Normal);
            _devSummary.horizontalOverflow = HorizontalWrapMode.Wrap;
            SetRect(_devSummary.rectTransform, new Vector2(0f, 0f), new Vector2(1f, 1f), new Vector2(0f, 1f), new Vector2(16f, 72f), new Vector2(-16f, -50f));
            var share = MakeButton("ShareLog", dev.transform, "SHARE LOG", () => DevCapture.Share());
            share.GetComponent<Image>().color = Accent;
            SetRect(share.GetComponent<RectTransform>(), new Vector2(0f, 0f), new Vector2(0f, 0f), new Vector2(0f, 0f), new Vector2(16f, 12f), new Vector2(206f, 60f));
            share.GetComponentInChildren<Text>().fontSize = 16;
            var copy = MakeButton("CopyLog", dev.transform, "COPY LOG", () => { DevCapture.Copy(); RefreshSettings(); });
            SetRect(copy.GetComponent<RectTransform>(), new Vector2(0f, 0f), new Vector2(0f, 0f), new Vector2(0f, 0f), new Vector2(216f, 12f), new Vector2(406f, 60f));
            copy.GetComponentInChildren<Text>().fontSize = 16;

            var hint = MakeText("SettingsHint", screen,
                "Button size and layout apply to FIRE / JUMP / ALT / WPN and the joystick. SHARE LOG opens the Android share sheet with the error report (send it to the developer).",
                12, TextAnchor.LowerLeft, SubText, FontStyle.Normal);
            SetRect(hint.rectTransform, new Vector2(0f, 0f), new Vector2(1f, 0f), new Vector2(0f, 0f), new Vector2(20f, 12f), new Vector2(-20f, 40f));
            return screen.gameObject;
        }

        Text StepperRow(RectTransform parent, string name, string caption, float y, UnityEngine.Events.UnityAction minus, UnityEngine.Events.UnityAction plus)
        {
            var label = MakeText(name + "Caption", parent, caption, 16, TextAnchor.MiddleLeft, TextColor, FontStyle.Bold);
            SetRect(label.rectTransform, new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(16f, y - 56f), new Vector2(300f, y));
            var m = MakeButton(name + "Minus", parent, "-", minus);
            SetRect(m.GetComponent<RectTransform>(), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(340f, y - 56f), new Vector2(400f, y));
            var value = MakeText(name + "Value", parent, "", 18, TextAnchor.MiddleCenter, Accent, FontStyle.Bold);
            SetRect(value.rectTransform, new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(404f, y - 56f), new Vector2(520f, y));
            var p = MakeButton(name + "Plus", parent, "+", plus);
            SetRect(p.GetComponent<RectTransform>(), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(524f, y - 56f), new Vector2(584f, y));
            return value;
        }

        Image ToggleRow(RectTransform parent, string name, string caption, float y, out Text stateLabel, UnityEngine.Events.UnityAction onClick)
        {
            var label = MakeText(name + "Caption", parent, caption, 16, TextAnchor.MiddleLeft, TextColor, FontStyle.Bold);
            SetRect(label.rectTransform, new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(16f, y - 56f), new Vector2(300f, y));
            var go = MakeButton(name, parent, "", onClick);
            SetRect(go.GetComponent<RectTransform>(), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(0f, 1f), new Vector2(340f, y - 56f), new Vector2(584f, y));
            stateLabel = go.GetComponentInChildren<Text>();
            stateLabel.fontSize = 16;
            return go.GetComponent<Image>();
        }

        void RefreshSettings()
        {
            if (_scaleValue == null) return;
            _scaleValue.text = TouchSettings.ButtonScale.ToString("0.0") + "×";
            _sensValue.text = TouchSettings.Sensitivity.ToString("0.0") + "×";
            _invertLabel.text = TouchSettings.InvertY ? "ON" : "OFF";
            _invertImg.color = TouchSettings.InvertY ? Accent : CardColor;
            _leftLabel.text = TouchSettings.LeftHanded ? "ON" : "OFF";
            _leftImg.color = TouchSettings.LeftHanded ? Accent : CardColor;
            var dc = DevCapture.Instance;
            _devSummary.text = "errors " + RuntimeErrorLog.ErrorCount + " · warnings " + RuntimeErrorLog.WarningCount +
                (dc != null && dc.SampleCount > 0 ? "\nlast: " + dc.LastSample : "") +
                (!string.IsNullOrEmpty(RuntimeErrorLog.LastError) ? "\nlast error: " + RuntimeErrorLog.LastError : "") +
                "\nlog file: " + RuntimeErrorLog.Path;
        }

        // ------------------------------------------------------------ helpers

        Image MakeImage(string name, Transform parent, Color color)
        {
            var go = new GameObject(name, typeof(RectTransform), typeof(Image));
            go.transform.SetParent(parent, false);
            var image = go.GetComponent<Image>();
            image.color = color;
            image.raycastTarget = false;
            return image;
        }

        Text MakeText(string name, Transform parent, string value, int size, TextAnchor anchor, Color color, FontStyle style)
        {
            var go = new GameObject(name, typeof(RectTransform), typeof(Text));
            go.transform.SetParent(parent, false);
            var text = go.GetComponent<Text>();
            text.font = _font;
            text.text = value;
            text.fontSize = size;
            text.alignment = anchor;
            text.color = color;
            text.fontStyle = style;
            text.raycastTarget = false;
            text.horizontalOverflow = HorizontalWrapMode.Wrap;
            text.verticalOverflow = VerticalWrapMode.Truncate;
            return text;
        }

        GameObject MakeButton(string name, Transform parent, string label, UnityEngine.Events.UnityAction onClick)
        {
            var go = new GameObject(name, typeof(RectTransform), typeof(Image), typeof(Button));
            go.transform.SetParent(parent, false);
            go.GetComponent<Image>().color = CardColor;
            var button = go.GetComponent<Button>();
            var colors = button.colors;
            colors.highlightedColor = CardPressed;
            colors.pressedColor = CardPressed;
            button.colors = colors;
            button.onClick.AddListener(onClick);
            var text = MakeText("Label", go.transform, label, 18, TextAnchor.MiddleCenter, TextColor, FontStyle.Bold);
            Stretch(text.rectTransform, Vector2.zero, Vector2.zero);
            return go;
        }

        static void Stretch(RectTransform rt, Vector2 min, Vector2 max)
        {
            rt.anchorMin = Vector2.zero;
            rt.anchorMax = Vector2.one;
            rt.offsetMin = min;
            rt.offsetMax = max;
        }

        static void SetRect(RectTransform rt, Vector2 anchorMin, Vector2 anchorMax, Vector2 pivot, Vector2 offsetMin, Vector2 offsetMax)
        {
            rt.anchorMin = anchorMin;
            rt.anchorMax = anchorMax;
            rt.pivot = pivot;
            rt.offsetMin = offsetMin;
            rt.offsetMax = offsetMax;
        }

        static void ApplySafeArea(RectTransform rt)
        {
            if (Screen.width <= 0 || Screen.height <= 0) return;
            Rect safe = Screen.safeArea;
            rt.anchorMin = new Vector2(safe.xMin / Screen.width, safe.yMin / Screen.height);
            rt.anchorMax = new Vector2(safe.xMax / Screen.width, safe.yMax / Screen.height);
            rt.offsetMin = Vector2.zero;
            rt.offsetMax = Vector2.zero;
        }
    }
}
